### ISSUE TITLE
Upstream handler for this

### ISSUE THREAD

**Issue by demonnic** [krystophv/mudletMAR#2]
It looks like this may have come about around the same time I formalized support for this in muddler itself with an mpackage I release alongside it. Has a new muddler option for writing an output file and pre/post handlers for install and remove for doing any cleanup between tests and such.

May be worth looking at to see if it covers your needs or may have additional functionality you'd like to use or roll into this. It's good to see muddler being used!

**Comment by krystophv** [comment]
You're correct in that this came out _just_ prior to the mpackage and output file in muddler. This project represents a relatively blunt instrument compared to the built-in handling in muddler. I may attempt to take advantage of it, but the thing that I kept tripping on was that the pathing for the output file wasn't correct when running the docker image for muddler from Windows. (crossing the docker -> Windows filesystem gap seems a bridge too far I guess?)

**Comment by demonnic** [comment]
So someone did mention this and there was a fix in one of the last couple of releases of muddler, if you get the mpackage from the latest muddler release it should work better for you.

**Comment by krystophv** [comment]
I believe the issue I have still exists. When running from the docker image:
`docker run --rm -v "%cd%":/cartographer -w /cartographer demonnic/muddler`
output path is: `"path": "/build/<package_name>.mpackage"`
and when I run from the directory just using the platform-native `muddle` command output path is:
`"path": "E:\<complete>\<directory>\<structure>\build\<package_name>.mpackage"`

I'll try the update to see if it's more than just the updated docker image that I need.

**Comment by demonnic** [comment]
Are you using the latest version of muddler as well? The path got changed in both at the same time, so you may need to docker pull. 

```
{ "name": "MDK", "path": "/build/MDK.mpackage" }
```

Is what it should look like now as an example.

**Comment by krystophv** [comment]
Ah yeah. I updated my "native" install and now it outputs 
```{ "name": "<package_name>", "path": "/build\<package_name>.mpackage" }```
where the docker image is:
```{ "name": "<package_name>", "path": "/build/<package_name>.mpackage" }```

The muddler mudlet package seems to choke on the path with mixed path separators, but the docker version is working fine it seems.

**Comment by demonnic** [comment]
Interesting, I'll file an issue in muddler and get a release out with the bugfix for that. I haven't used muddler natively in windows except to prove I could, didn't test the bridge. Thanks for letting me know =)

**Comment by demonnic** [comment]
ok, have fixed it in both muddler itself and in the mpackage, will be releasing them in a bit here. Mistakenly hardcoded the `/` at the beginning of the path and switched it to use the defined file separator, so it'll match. But I also setup the bridge mpackage to change it all to / since Lua can use that on all three OSes without issue, just doesn't like mixing them so much.

**Comment by demonnic** [comment]
hmm, actually, having had a bit more testing I'm going to change it to use `/` regardless, since Lua will just work that way... the `\` is causing json parsing errors and I would rather just standardize on `/` than hack around it.

**Comment by demonnic** [comment]
https://github.com/demonnic/muddler/releases/tag/0.11 should resolve your issues with the ci bridge. If not, let me know. I'm gonna go ahead and close this out as I'm not intending to badger you into using it or anything, I just couldn't think of a better way to contact you about it.
